@echo off
set DB_USER=postgres
set DB_PASSWORD=spirit
set DB_NAME=Presenca_Transporte
set DB_HOST=localhost
set DB_PORT=5432
set AUTH_SERVICE_URL=http://localhost:8081
set AUTH_SERVICE_JWT_SECRET=dev-secret-change-me-dev-secret-change-me
set ROUTE_GEN_MODE=auto
set ROUTE_GEN_URL=http://localhost:5001/api/routes/generate
set EFFECTIVE_PRESENCE_SECONDS=30
node calendar-server.js
