spring.application.name=presenca-service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/presenca_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:presenca_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:presenca_pass}
server.port=8082
logging.level.root=INFO
logging.level.com.transportation.presenca=INFO
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
